# .readthedocs.yml
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
    - requirements: requirements.txt
    - requirements: dev-requirements.txt
